app_book:
    resource: "@AppBundle/Resources/config/routing/book.yml"
    prefix:   /book
app_author:
    resource: "@AppBundle/Resources/config/routing/author.yml"
    prefix:   /author
app_genre:
    resource: "@AppBundle/Resources/config/routing/genre.yml"
    prefix:   /genre
app_home:
    path:     /
    defaults: { _controller: "AppBundle:Book:index" }
    methods:  GET


