AppBundle\Entity\Book:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BookRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        publicationDate:
            type: date
        catalogDate:
            type: datetimetz
        image:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks:
        prePersist: [prePersist]

    manyToOne:
        genre:
          targetEntity: AppBundle\Entity\Genre
          inversedBy: books
        author:
            targetEntity: AppBundle\Entity\Author
            inversedBy: books