AppBundle\Entity\Book:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BookRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        publicationDate:
            type: date
        catalogDate:
            type: date
        rating:
            type: float
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        genre:
          targetEntity: AppBundle\Entity\Genre
          joinColumn:
            name: genre_id
            referencedColumnName: id

    manyToOne:
        author:
            targetEntity: AppBundle\Entity\Author
            inversedBy: books