AppBundle\Entity\Genre:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GenreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }