AppBundle\Entity\Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        fileName:
            type: string
            length: 255
            unique: true