AppBundle\Entity\User:
  type:  entity
  table: fos_user
  id:
      id:
        type: integer
        id: true
        generator:
            strategy: AUTO
  fields:
      name:
          type: string
          length: 255
          unique: true
  oneToOne:
    image:
      targetEntity: AppBundle\Entity\Image
      joinColumn:
        name: image
        referencedColumnName: id
        onDelete: restrict